### ISSUE TITLE
Невозможно поставить следующий трек

### ISSUE THREAD

**Issue by Daizygod** [Daizygod/sukify#29]

**Comment by el1xz** [comment]
Daizy, thank you for your feedback. We've been working days and nights to fix this bug. And now you can finally use the new version of Sukify. You can now easily switch tracks, put the next track on, and when a track ends, the next track will automatically start automatically. With love , your humble servant and developer and f *_* k your .... эликзиз.

**Comment by Daizygod** [comment]
> Daizy, thank you for your feedback. We've been working days and nights to fix this bug. And now you can finally use the new version of Sukify. You can now easily switch tracks, put the next track on, and when a track ends, the next track will automatically start automatically. With love , your humble servant and developer and f ___ k your .... эликзиз.

thank you very much my friend
